### ISSUE TITLE
Multiple bbox per image ? 

### ISSUE THREAD

**Issue by mbertalan** [datitran/raccoon-dataset#1]
Hej Dan ! Very nice your raccoon-dataset. I am working in a similar problem and I am having trouble to find information of how to create TFrecord when a image has multiple labels (object/bbox).

For example, in your CSV file you have one image per line with one box. But how would you do if there are two boxes ? Would you just add another line ?

Example:
filename	width	height	class	xmin	ymin	xmax	ymax
raccoon-17.jpg	259	194	raccoon	95	60	167	118 
raccoon-17.jpg	259	194	cat	35	90	67	11 

Thank you very much for sharing your code.

**Comment by datitran** [comment]
It's Dat not Dan:) And to your question, yes you are correct, just add another line. In my csv, I also have images where there are two raccoons on this image, for example, see image raccoon-117.jpg

raccoon-117.jpg	640	448	raccoon	100	124	266	324
raccoon-117.jpg	640	448	raccoon	342	101	570	297

If you have more classes, the same concept applies. Only the class name changes, the script is able to take care of it. Personally, I prefer my way to create TFRecords out of the csv file instead of the PASCAL VOC or Oxford Pet script that the TF API provided as I'm more flexible in creating the train/test dataset out of one csv. Hope this helps!

**Comment by mbertalan** [comment]
Hej Dat ! Sorry for misspelling :-) 

Yes, I figure it out and I managed to make it work in my own data. I think the difficult is the scripts are always specific to a example. So, there is always some re-coding to make it work with your own data. 

Thanks for sharing it and replying. It was very useful to see your code and the details in your blog. I understand TFrecords a bit more now. 
My Best Regards

**Comment by ParichayDidwania** [comment]
Hey Dat, I was wondering instead of having another line can we add them in the same row, like min-x could have 2 elements [100,342] and same for others? This would avoid repetition of images in the tfrecord and thus reduce the size of tfrecord. Is this possible to be trained on such tfrecord?
